### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by josephgupkim** [kgraskamp/teacozy#3]
In relation to the text overlap in the Contact section, the copyright text should be hugging the left site of the screen.

https://github.com/kgraskamp/teacozy/blob/master/index.html#L84

**Comment by kgraskamp** [comment]
I really struggled with this part. It initially appeared correctly, but I modified something that wasn't even in the footer and couldn't get it back to the left-hand side. I tried padding, margin, justify content, align items, and align content.
