### ISSUE TITLE
Nav Color

### ISSUE THREAD

**Issue by josephgupkim** [kgraskamp/teacozy#4]
Although not an big issue, when looking at the design specs, the nav links are colored white while yours is still blue. You should try to give it a tackle!

https://github.com/kgraskamp/teacozy/blob/master/index.html#L12-L16

**Comment by kgraskamp** [comment]
Yes I couldn't figure it out! I had a .nav span { on the stylesheet but was unable to get anything modified. Was my selector incorrect?
