### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by josephgupkim** [kgraskamp/teacozy#5]
Your project submission looks great! Looks almost identical structurally but could use some slight adjustments:
Overlapping of the Contact text with Copyright text.
Copyright text should be aligned on left side.
Nav links color changed to white.
I think with these fixes your site will be pretty much identical! Great work so far as I love the organization of both your files and your stylesheet. Keep up the great work. Will look forward to seeing future projects!

Grade: Meets Expectation.

**Comment by kgraskamp** [comment]
Thank you so much for the review and advice!
